apiVersion: v1
kind: Service
metadata:
  name: spring-angular-app-service
spec:
  selector:
    app: spring-angular-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: LoadBalancer

